Rails update
shunjuio/ec_app_nomura pull request #6
Opened 2023-10-30 05:11 UTC by yo-gari

## 何を解決するのか

Ruby3.2.2とRails7.1.1のアップデート

## レビュー関連

- 該当タスク：[RubyとRailsのversionを最新の安定版にする](https://www.notion.so/shunju/Ruby-Rails-version-8c9febca4e0a4c4d9e0d778012657d93?pvs=4)

### 不安なところ・特に見てほしいところ

テスト環境のgem debaseを不要のため、削除しました。

### レビューポイント

bundle updateによって、RubyとRails以外にもgemが新しいバージョンになっています。
Rails7の影響で、pumaを5から6にアップデートしています。
Rubyのアップデートによって、to_s(:delimited)がto_fs(:delimited)へ変更になっています。
ActiveSupport::Cacheの利用中バージョンが次回Railsのアップデートでサポートされなくなるため、アップデートを実施しました。

### 動作確認（実装状況のスクショなど）
<details>
  <summary>
    実施状況
  </summary>
<img width="646" alt="スクリーンショット 2023-10-27 19 11 24" src="https://github.com/shunjuio/ec_app_nomura/assets/105269891/6753ac2d-cc8e-4ee0-bc32-462db1f332e5">
</details>

2023-11-14 04:39 UTC, aratai-2023 commented
> テスト環境のgem debaseのバージョンを0.2.5.beta2に変更して、DBに接続できないエラーを解消しました。
beta版というところが気になっていますが、問題ないですか？

beta版はなるべく使用しない方向にしましょう。debaseとruby-debug-ide（依存関係）はuninstallして問題ないと思います。
昨日pryでのデバッグについてせっかく習っているので、デバッグはpry-byebug, pry-railsを導入してpryを使うようにしましょうか👍
docker環境でbinding.pryで処理を中断させるためには、docker-compose.ymlのapp配下に以下の2行を追記する必要があります。
```docker
tty: true
stdin_open: true
```
pry関連のgem導入とdocker-compose.ymlの設定の修正をお願いします🙏

2023-11-14 04:39 UTC, aratai-2023 requested changes

2023-11-14 04:57 UTC, yo-gari commented on Gemfile
修正しました。

2023-11-14 05:05 UTC, yo-gari commented on app/views/cart/index.html.erb
> +      <p><%= cart.product.price.to_formatted_s(:delimited) %>円</p>
全部のviewを修正しました。

2023-11-14 06:14 UTC, yo-gari commented
> > テスト環境のgem debaseのバージョンを0.2.5.beta2に変更して、DBに接続できないエラーを解消しました。
> > beta版というところが気になっていますが、問題ないですか？
> 
> beta版はなるべく使用しない方向にしましょう。`debase`と`ruby-debug-ide`（依存関係）はuninstallして問題ないと思います。 昨日pryでのデバッグについてせっかく習っているので、デバッグは`pry-byebug`, `pry-rails`を導入してpryを使うようにしましょうか👍 docker環境で`binding.pry`で処理を中断させるためには、docker-compose.ymlのapp配下に以下の2行を追記する必要があります。（詳細はググってみてください）
> 
> ```
> tty: true
> stdin_open: true
> ```
> 
> pry関連のgem導入とdocker-compose.ymlの設定の修正をお願いします🙏

pry関連の導入と`debase`と`ruby-debug-ide`をgemから削除しました。

2023-11-15 00:14 UTC, aratai-2023 approved these changes

2023-11-15 00:14 UTC, aratai-2023 commented on docker-compose.yml
> +    tty: true
この記述順にした意図って何かありますか？

2023-11-15 00:14 UTC, merged

2023-11-15 01:00 UTC, yo-gari commented on docker-compose.yml
> +    tty: true
意図して順番を決めたわけではありません。
参考にしたサイトがその順番だったのでそのまま記述しました。

2023-11-15 06:18 UTC, yo-gari commented on app/views/cart/index.html.erb
> +      <p><%= cart.product.price.to_formatted_s(:delimited) %>円</p>
[](フィードバックを受けて改めてコメントを考えてみた)
参考にしたサイトにaliasはなかったのでアドバイス助かります。ありがとうございます。
他のviewについてもto_fsに修正しました。

2023-11-15 06:26 UTC, yo-gari commented on Gemfile
フィードバックを受けて改めてコメントを考えてみました。

group :development, :testが2つ直近で気づいたので、次のPRで修正することを考えていました。
group :developmentも2つあったのは気づかなかったです。今回は、アドバイス通りにリファクタリングを行い、fackerにバージョンを明記しました。